### ISSUE TITLE
Set custom action bar

### ISSUE THREAD

**Issue by ArbazIn** [RupinS/CardDrawer#2]
Hi Rupin,
Your CardDrawerLayout example is superb, i just download and run the project in to  tablet issue is in action bar back icon.
how to solved this issue?
reply me ASAP

**Comment by RupinSahu** [comment]
Thanks @ArbazGitHub for using my CardDrawer. Sorry, for seeing your issue lately. Can you please share some more info about the issue like where the problem is occuring exactly, where are you using my library (piece of code will be great), what is the version of Android on tablet and have you debugged your code. You can reply me here or dm me on my mail rupinsahu007@gmail.com. Will be pleasure if I can help you!
